### ISSUE TITLE
Firebase java.lang.NoClassDefFoundError crash

### ISSUE THREAD

**Issue by chrispypatt** [Savour-Deals/Savour-Flutter#35]
Maybe this is because savour defined  ext.kotlin_version = '1.3.21' while app_settings plugin defined as  ext.kotlin_version = '1.3.20'. The first thing to try is if changing to match will mitigate this.

`Fatal Exception: java.lang.NoClassDefFoundError: kotlin.jvm.internal.Intrinsics
       at com.example.appsettings.AppSettingsPlugin$Companion.registerWith(AppSettingsPlugin.kt)
       at com.example.appsettings.AppSettingsPlugin.registerWith(AppSettingsPlugin.kt)
       at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:33)
       at com.CP.Savour.MainActivity.onCreate(MainActivity.java:11)
       at android.app.Activity.performCreate(Activity.java:5372)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
       at android.app.ActivityThread.access$700(ActivityThread.java:159)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5419)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by chrispypatt** [comment]
Identified this occurs when android version is on sdk 19 and below. We do not need to support these.
